# Generated by Django 4.1 on 2022-08-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 28, 49, 434581, tzinfo=datetime.timezone.utc))),
                ('featured', models.BooleanField(default=False)),
                ('image', models.TextField(max_length=30)),
            ],
        ),
    ]
