# Generated by Django 4.1 on 2022-08-16 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='website_link',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 18, 39, 46, 673842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=25)),
                ('projects', models.ManyToManyField(blank=True, null=True, related_name='tags', to='main.project')),
            ],
        ),
    ]
