# Generated by Django 4.1 on 2022-08-16 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_date_alter_projecttag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.TextField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 16, 23, 29, 30, 831876, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
