# Generated by Django 4.1 on 2022-08-17 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_blurb_alter_project_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 17, 21, 26, 34, 442181, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
