# Generated by Django 4.1 on 2022-09-14 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 10, 22, 18, 509570), null=True),
        ),
        migrations.AlterField(
            model_name='projecttag',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.project'),
        ),
    ]
