# Generated by Django 4.1 on 2022-10-06 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_project_date_alter_projecttag_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 22, 6, 18, 334408), null=True),
        ),
    ]
