# Generated by Django 4.1 on 2022-10-06 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 6, 22, 7, 32, 843268), null=True),
        ),
    ]
