# Generated by Django 4.1.2 on 2023-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='htmlLink',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
