# Generated by Django 4.1.2 on 2023-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_project_htmllink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='htmlLink',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
