# Generated by Django 4.1.2 on 2023-02-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_project_htmllink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='htmlLink',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
