# Generated by Django 4.1.2 on 2023-06-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_project_htmllink'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='tmp', max_length=255),
            preserve_default=False,
        ),
    ]
