# Generated by Django 4.1.2 on 2023-06-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
